### ISSUE TITLE
Let's make a roadmap together!

### ISSUE THREAD

**Issue by xpepper** [xpeppers/starway-to-orione#6]
Dear contributors, 
I'd like to discuss with you some topics about the roadmap for this project, e.g.
- What should we go with StarwayToOrione?
- How should we mix the paths together?
- How should we organize all the available paths so that everyone can make up its own path?

I have some ideas but need yours.
What about an hangout one of these days? 

@pdincau @christian-fei @filippo-liverani @ivoputzer @xpeppers/orione-team

**Comment by pdincau** [comment]
I will close this issue. This repository has moved on and therefore the isssue has no sense anymore.
